-- 1 Base de dados e criação de tabela

CREATE TABLE student_prediction(
    cod_student SERIAL PRIMARY KEY,
    studentid VARCHAR(20),
    age INT,
    gender INT,
    hs_type INT,
    scholarship INT,
    work INT,
    activity INT,
    partner INT,
    salary INT,
    transport INT,
    living INT,
    mother_edu INT,
    father_edu INT,
    siblings INT,
    kids INT,
    mother_job INT,
    father_job INT,
    study_hrs INT,
    read_freq INT,
    read_freq_sci INT,
    attend_dept INT,
    impact INT,
    attend INT,
    prep_study INT,
    prep_exam INT,
    notes INT,
    listens INT,
    likes_discuss INT,
    classroom INT,
    cuml_gpa INT,
    exp_gpa INT,
    course_id INT,
    grade INT
);